// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sohyviltwgpuslbjzqzh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvaHl2aWx0d2dwdXNsYmp6cXpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ2MDkyMTQsImV4cCI6MjA4MDE4NTIxNH0.YgdW-yrzKf-N7SGlFDUfkor8jaF2RW-bdPrvP6csvyE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});